// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sua_phieumuon_ngaytra_docgia_mathetv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sua_phieumuon_ngaytra_docgia_mathetv));
        
        string IMigrationMetadata.Id
        {
            get { return "201611191453031_Sua_phieumuon_ngaytra_docgia_mathetv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
